---
language: python
python:
    - '3.6'  # EOL 2021-12-23
    - '3.7'  # EOL 2023-06-27
    - '3.8'  # EOL 2024-10
    - 3.9-dev   # EOL 2025-10
    - nightly
matrix:
    allow_failures:
        - python: 3.9-dev
        - python: nightly
    fast_finish: true

cache:
    pip: true
    directories:
        - $HOME/.cache/pre-commit

install:
    - pip install --upgrade pip
    - pip install pre-commit
    - pre-commit install-hooks
    - pip install poetry
    - poetry install -v

script:
    - pre-commit run --all-files
    - vulture --min-confidence=61 --exclude=zfs/replicate/cli/click.py --ignore-names=main zfs  # yamllint disable-line
    - zfs-replicate --help
    - pytest
    - poetry build
    - tar -zvtf dist/zfs-replicate-*.tar.gz | grep zfs/replicate/

after_success:
    - coveralls

before_deploy:
    # User and password environment variables are set as hidden variables
    # through the web interface in the project settings.
    - pip install --upgrade pip
    - pip install poetry
    - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
    - poetry build

deploy:
    provider: script
    script: poetry publish
    skip_cleanup: true
    on:  # yamllint disable-line
        all_branches: true  # Travis recognizes tag names as "branches"
        condition: $TRAVIS_BUILD_STAGE_NAME = Deploy
        repo: alunduil/zfs-replicate
        tags: true
